using RestaurantCity;
using System.Text.Json;
int passed = 0;
void Check(bool result, string label) { if (!result) throw new Exception(label); passed++; Console.WriteLine("PASS " + label); }
var cash = new GameState { Cash = 149 };
var r = new RestaurantState();
Check(!r.BuyRestaurant(cash, out _) && !r.Owned && cash.Cash == 149, "purchase requires $150, atomic");
cash.Cash = 150;
Check(r.BuyRestaurant(cash, out _) && r.Owned && cash.Cash == 0, "purchase restaurant");
Check(r.Layout.Count == 7 && r.Produce > 0 && r.Protein > 0 && r.Seats == 2, "purchase includes useful starter kit");
Check(!r.Sell(cash,r.Layout.First(p=>p.CatalogId=="prep_bench").InstanceId,out _), "last prep bench protected from unrecoverable sale");
Check(!r.Sell(cash,r.Layout.First(p=>p.CatalogId=="grill").InstanceId,out _), "last grill protected from unrecoverable sale");
Check(!r.Sell(cash,r.Layout.First(p=>p.CatalogId=="cafe_table").InstanceId,out _), "last seating protected from unrecoverable sale");
Check(!r.BuyRestaurant(cash, out _), "cannot purchase twice");
Check(RestaurantCatalog.Items.Length == 28, "28 distinct catalog items");
Check(!r.CanPlace("cafe_table",5,4,0,-1,out _), "central aisle protected");
Check(!r.CanPlace("cafe_table",11,4,0,-1,out _), "bounds protected");
Check(!r.CanPlace("cafe_table",0,0,0,-1,out _), "overlap prevented");
cash.Cash = 1000;
Check(r.Place(cash,"booth_teal",0,5,1,out _), "rotated furniture can be purchased");
var booth=r.Layout.Last();
Check(!r.Move(booth.InstanceId,0,0,0,out _), "move collision retains old layout");
Check(booth.X == 0 && booth.Z == 5, "failed move atomic");
int before = cash.Cash;
Check(r.Sell(cash,booth.InstanceId,out _) && cash.Cash == before+RestaurantCatalog.Find("booth_teal").Price/2, "resale half paid value");
Check(!r.Sell(cash,booth.InstanceId,out _), "sold item cannot be sold twice");
Check(r.Place(cash,"wall_teal",0,0,0,out _) && r.WallId == "wall_teal", "wall finish persists");
Check(!r.Place(cash,"wall_teal",0,0,0,out _), "same finish rejected");
Check(!r.Place(cash,"sign_neon",0,0,0,out _), "two-star catalog gate");
Check(!r.ToggleDish(cash,"midnight",out _), "midnight locked before city recipe");
cash.RecipeUnlocked=true;
Check(r.ToggleDish(cash,"midnight",out _) && r.ActiveMenu.Contains("midnight"), "city recipe opens restaurant menu");
Check(r.StartService(cash,out _), "start ongoing restaurant service");
var table=r.Layout.First(p=>p.CatalogId=="cafe_table");
Check(!r.Sell(cash,table.InstanceId,out _), "active service protects tables");
var order = r.AddCustomer(cash,0,table.InstanceId,out _);
Check(order != null && order.Stage==RestaurantOrderStage.Waiting, "customer takes order");
Check(r.BeginCooking(order.Id,out _), "cooking consumes ingredient stock");
r.Tick(cash,15);
Check(order.Stage==RestaurantOrderStage.Ready, "cooking completes");
before=cash.Cash;
Check(r.CompleteServing(cash,order.Id,out _) && cash.Cash>before, "serving pays and satisfies");
Check(r.Reviews.Count==1 && r.Reviews[0].Comment.Contains("Food") && r.Reviews[0].Comment.Contains("wait"), "reviews explain food and wait");
Check(!r.CompleteServing(cash,order.Id,out _), "cannot double serve");
r.Tick(cash,20);
Check(r.EndService(out _), "service can close after diners depart");
r.Tick(cash,7);
Check(r.Hire(cash,"ember",out _) && !r.Hire(cash,"ember",out _), "hire robot once");
Check(r.Assign("ember",StaffJob.Cook,out _) && r.WorkerActionSeconds(StaffJob.Cook)<r.WorkerActionSeconds(StaffJob.Serve), "chef strength affects speed");
var options=new JsonSerializerOptions { IncludeFields=true, IgnoreReadOnlyProperties=true };
var loaded=JsonSerializer.Deserialize<RestaurantState>(JsonSerializer.Serialize(r,options),options);
loaded.SanitizeAfterLoad();
Check(loaded.Owned && loaded.WallId==r.WallId && loaded.Layout.Count==r.Layout.Count && loaded.Workers.Count==1, "whole layout and workers round-trip");
Check(!loaded.Open && loaded.Orders.Count==0, "load settles unfinished service without duplicate payments");
Check(RestaurantCatalog.Customers.Length==8 && RestaurantCatalog.Customers.Select(c=>c.Name).Distinct().Count()==8, "eight authored customer types");
Check(RestaurantCatalog.Staff.Length==2 && RestaurantCatalog.Staff[0].Role!=RestaurantCatalog.Staff[1].Role, "distinct staff specialties");
Check(!r.Place(cash,"fern",0,0,8,out _), "invalid rotation rejected");
Check(r.Place(cash,"floor_checker",0,0,0,out _) && r.FloorId=="floor_checker", "floor applies independently of wall");
Check(r.Place(cash,"wall_rose",0,0,0,out _) && r.Layout.Count(p=>p.CatalogId.StartsWith("wall_"))==1, "replacement finish never duplicates benefits");
Check(r.Place(cash,"pendant_amber",0,3,0,out _), "overhead lights allowed over tables");
Check(r.Place(cash,"rug_sunset",0,3,0,out _), "rug allowed under tables");
Check(r.Place(cash,"fern",8,7,0,out _), "decoration adds visible ambience");
Check(r.Ambience>=12, "several affordable upgrades meet ambience goal");
r.StartService(cash,out _);
order=r.AddCustomer(cash,3,table.InstanceId,out _);
Check(order!=null, "second service remains playable");
int missed=r.Lost;
r.Tick(cash,RestaurantCatalog.Customers[order.CustomerType].Patience+1);
Check(order.Stage==RestaurantOrderStage.Leaving && r.Lost==missed+1 && r.Reviews[0].Comment.Contains("hungry"), "timeout gives explanatory negative review");
r.Tick(cash,7);
Check(!r.Orders.Contains(order), "departed customers removed");
r.EndService(out _);
// Deterministic full progression loop, exercising purchases, stocking, serving and repeated shifts.
cash.Cash=1000;r.ActiveMenu=new List<string>{"burger"};
for(int i=0;i<24;i++) {
    if(!r.Open) Check(r.StartService(cash,out _), "repeat service opens");
    while(r.Protein<1) Check(r.Restock(cash,true,out _), "restock protein");
    while(r.Produce<1) Check(r.Restock(cash,false,out _), "restock produce");
    r.Clean(out _);
    var meal=r.AddCustomer(cash,i%8,table.InstanceId,out _);
    Check(meal!=null&&r.BeginCooking(meal.Id,out _), "progression order starts");
    r.Tick(cash,10);
    Check(r.CompleteServing(cash,meal.Id,out _), "progression order pays");
    r.Tick(cash,9);r.Tick(cash,7);
    if(i%6==5)r.EndService(out _);
}
Check(r.Stars==2 && r.Satisfaction>=75, "restaurant grows to two stars through real service");
Check(PlaceFree(r,cash,"oven") && r.ToggleDish(cash,"dessert",out _), "two-star reward unlocks new equipment and dish");
Check(r.Place(cash,"sign_neon",0,0,0,out _), "two stars unlock visible frontage reward");
Check(r.Hire(cash,"moss",out _) && r.Assign("moss",StaffJob.Clean,out _), "second worker can take cleaning job");
Check(r.WorkerActionSeconds(StaffJob.Clean)==3, "Moss cleaning specialty effective");
Check(r.WagesPerOrder==2, "ongoing wages explicit for two active workers");
r.Assign("moss",StaffJob.Off,out _);
Check(r.WagesPerOrder==1, "off-duty worker charges no wage");
int stockBefore=r.Produce;r.Produce=r.StockLimit;before=cash.Cash;
Check(!r.Restock(cash,false,out _) && cash.Cash==before, "full storage cannot charge cash");
r.Produce=stockBefore;
Check(PlaceFree(r,cash,"fridge") && r.StockLimit==48, "fridge doubles stock limit");
var snapshot=JsonSerializer.Deserialize<RestaurantState>(JsonSerializer.Serialize(r,options),options);snapshot.SanitizeAfterLoad();
Check(snapshot.Stars==2 && !snapshot.ActiveMenu.Contains("dessert") && snapshot.ActiveMenu.SequenceEqual(r.ActiveMenu.Where(id=>id!="dessert")) && snapshot.Reviews.Count==r.Reviews.Count && snapshot.Workers.Count==2, "progression menu reviews and staff persist");
var stranded=new RestaurantState();var poor=new GameState{Cash=150};stranded.BuyRestaurant(poor,out _);stranded.Produce=0;stranded.Protein=0;stranded.ActiveMenu=new List<string>{"burger"};
Check(stranded.RequestSupplyHelp(poor,out _) && stranded.Produce==2 && stranded.ActiveMenu.Contains("salad"), "zero-cash restaurant gets a playable recovery dish");
Check(!stranded.RequestSupplyHelp(poor,out _), "cannot collect unlimited free supply packs");
var broken=new RestaurantState{Owned=true};
broken.Layout.Add(new PlacedItem{InstanceId=1,CatalogId="fern",X=-100,Z=2});
broken.Layout.Add(new PlacedItem{InstanceId=1,CatalogId="fern",X=1,Z=2});
broken.Layout.Add(new PlacedItem{InstanceId=1,CatalogId="fern",X=9,Z=2});
broken.SanitizeAfterLoad();
Check(broken.Layout.Count(p=>p.CatalogId=="fern")==2 && broken.Layout.Select(p=>p.InstanceId).Distinct().Count()==broken.Layout.Count, "load sanitizes bounds and duplicate identities");
var routing=new RestaurantState{Owned=true};cash.Cash=1000;
Check(routing.Place(cash,"stove",10,8,0,out _), "isolated kitchen station can be placed");
Check(routing.Place(cash,"fern",9,8,0,out _) && routing.Place(cash,"fern",10,7,0,out _) && routing.Place(cash,"fern",10,9,0,out _), "partial surrounds retain a path to kitchen");
Check(!routing.Place(cash,"fern",11,8,0,out _), "placement cannot seal off a kitchen station");
var menuTest=new RestaurantState();cash.Cash=1000;menuTest.BuyRestaurant(cash,out _);
Check(!menuTest.ToggleDish(cash,"soup",out _), "soup needs a stove");
Check(PlaceFree(menuTest,cash,"stove") && menuTest.ToggleDish(cash,"soup",out _), "stove unlocks soup");
menuTest.StartService(cash,out _);menuTest.ActiveMenu=new List<string>{"burger"};
int seatId=menuTest.Layout.First(p=>p.CatalogId=="cafe_table").InstanceId;
var a=menuTest.AddCustomer(cash,0,seatId,out _);var b=menuTest.AddCustomer(cash,1,seatId,out _);
Check(menuTest.AddCustomer(cash,2,seatId,out _)==null, "table capacity enforced");
Check(menuTest.BeginCooking(a.Id,out _) && menuTest.BeginCooking(b.Id,out _), "equipment expansion supports simultaneous cooking");
menuTest.Tick(cash,10);menuTest.CompleteServing(cash,a.Id,out _);float fresh=menuTest.Reviews[0].Score;
menuTest.Tick(cash,45);menuTest.Cleanliness=0;menuTest.CompleteServing(cash,b.Id,out _);
Check(menuTest.Reviews[0].Score<fresh && menuTest.Reviews[0].Comment.Contains("Food cooled") && menuTest.Reviews[0].Comment.Contains("dirty"), "cold food and dirty restaurant produce worse explained satisfaction");
Console.WriteLine($"{passed} restaurant checks passed");



static bool PlaceFree(RestaurantState r,GameState wallet,string id){for(int z=0;z<10;z++)for(int x=0;x<12;x++)if(r.CanPlace(id,x,z,0,-1,out _))return r.Place(wallet,id,x,z,0,out _);return false;}
